---
# vars file for test
components:
  - rustfmt
  - clippy-preview
  - rust-analyzer
  - rust-analysis
  - rust-src
targets:
  - x86_64-unknown-none
  - x86_64-unknown-linux-gnu
  - x86_64-unknown-linux-musl
  - x86_64-pc-windows-gnu
  - x86_64-pc-windows-msvc
  - wasm32-unknown-unknown
  - wasm32-wasip1
tools:
  - cargo-audit
  - cargo-shuttle
  - cargo-watch
  - cbindgen
  - just
  - trunk
