---
# tasks file for rust
- name: Install Rust and Cargo
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.cargo/bin/cargo

- name: Update PATH for all users
  become: true
  lineinfile:
    path: /etc/profile.d/cargo.sh
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: yes
    state: present

- name: Source the new PATH
  shell: source /etc/profile.d/cargo.sh
  args:
    executable: /bin/bash

- name: Install component
  shell: source /etc/profile && rustup component add {{ item }}
  loop: "{{ components }}"
  tags:
    - rust
  args:
    executable: /bin/bash

- name: Install tool
  shell: source /etc/profile && cargo install {{ item }}
  loop: "{{ tools }}"
  tags:
    - rust
  args:
    executable: /bin/bash
