alias grep='grep --color'
alias egrep='egrep --color'
alias tree='tree -C'

export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"

# Set PS1
__PS1_BLUE="\[$(tput setaf 4)\]"
__PS1_CYAN="\[$(tput setaf 6)\]"
__PS1_GREEN="\[$(tput setaf 2)\]"
__PS1_RED="\[$(tput setaf 1)\]"
__PS1_YELLOW="\[$(tput setaf 3)\]"
__PS1_CLEAR="\[$(tput sgr0)\]"
export PS1="${__PS1_RED}[\A]${__PS1_GREEN} \u@\h:${__PS1_CLEAR}[${__PS1_CYAN}\W${__PS1_CLEAR}]# "
