---
# tasks file for zsh
- name: Install Zsh
  become: true
  package:
    name: zsh
    state: present

- name: Set Zsh as default shell
  become: true
  shell: chsh -s $(which zsh) {{ ansible_user_id }}

- name: Check if Oh My Zsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_installed

- name: Download Oh My Zsh installation script
  when: not oh_my_zsh_installed.stat.exists
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh-install.sh
    mode: '0755'

- name: Execute the installation script
  when: not oh_my_zsh_installed.stat.exists
  shell: /tmp/ohmyzsh-install.sh

- name: Clean up the installation script
  when: not oh_my_zsh_installed.stat.exists
  file:
    path: /tmp/ohmyzsh-install.sh
    state: absent

- name: Add text block from a file
  blockinfile:
    path: ~/.zshrc
    block: "{{ lookup('file', 'files/zshrc') }}"
    create: yes
    state: present

- name: Install autosuggestions
  vars:
    oh_my_zsh_custom: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git 
    dest: "{{ oh_my_zsh_custom }}/plugins/zsh-autosuggestions"

- name: Install syntax-highlighting 
  vars:
    oh_my_zsh_custom: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ oh_my_zsh_custom }}/plugins/zsh-syntax-highlighting"

- name: Add plugins support in config
  replace:
    path: ~/.zshrc
    regexp: 'plugins=\((\w+)\)'
    replace: 'plugins=(\1 zsh-autosuggestions zsh-syntax-highlighting)'
