# playbook.yml
- hosts: localhost
  gather_facts: true

  vars:
    user: "{{ ansible_user_id }}"

  pre_tasks:
    - name: Test {{ user }}
      shell: echo {{ user }}

  roles:
    #- bash
    #- common
    #- git
    #- nvim
    #- rust
    - tmux
    #- zellij
    #- zsh

