name: Deploy container image

on:
  push:
    branches:
      - "develop"
    paths:
      - "Dockerfile"
      - ".github/workflows/deploy_ctr_image.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USER_NAME: dev
  USER_ID: 1000
  GROUP_ID: 1000
  GO_VERSION: 1.24.0
  HOSTNAME: dev-env

jobs:
  image:
    name: Release container image
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            USER_NAME=${{ env.USER_NAME }}
            USER_ID=${{ env.USER_ID }}
            GROUP_ID=${{ env.GROUP_ID }}
            GO_VERSION=${{ env.GO_VERSION }}
            HOSTNAME=${{ runner.HOSTNAME }}
